import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footers from '@/components/Footer'
import BackToTopButton from '@/components/Backtotop'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <BackToTopButton/>
        <Footers/>
    </html>
  )
}
